import turtle as trtl
painter = trtl.Turtle()
painter.fillcolor("darkred")


#house square structure walls thingy idk????
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.right(90)
painter.forward(100)

#roof
painter.begin_fill()
painter.right(45)
painter.forward(71)
painter.right(90)
painter.forward(71)
painter.end_fill()

#door
painter.penup()
painter.right(45)
painter.forward(100)
painter.right(90)
painter.forward(60)
painter.right(90)
painter.pendown()
painter.forward(35)
painter.right(90)
painter.forward(20)
painter.right(90)
painter.forward(35)
painter.penup()
painter.right(180)
painter.forward(20)
painter.left(90)
painter.forward(1)
painter.pendown()
painter.forward(3)

#window
painter.penup()
painter.right(90)
painter.forward(25)
painter.right(90)
painter.forward(30)
painter.pendown()
painter.left(90)
painter.forward(15)
painter.left(90)
painter.forward(15)
painter.left(90)
painter.forward(15)
painter.left(90)
painter.forward(15)
painter.penup()
painter.right(180)
painter.forward(7.5)
painter.right(90)
painter.pendown()
painter.forward(15)
painter.penup()
painter.right(90)
painter.forward(7.5)
painter.right(90)
painter.forward(7.5)
painter.right(90)
painter.pendown()
painter.forward(15)

#mustang car
painter.penup()
painter.left(90)
painter.forward(75)
#something?
wn = trtl.Screen()
wn.mainloop()

